### ISSUE TITLE
Spinner writing many times to console instead of updating in pre commit hook

### ISSUE THREAD

**Issue by bawahakim** [hyiso/lint_staged#14]
When running `dart run lint_staged`, the spinner behaves as expected: it spins in the same line, then updates with a check. 
When running with a pre commit hook like husky, the output is multiple lines, making it harder to find the true log.

![image](https://github.com/hyiso/lint_staged/assets/43802542/3bd6a88d-dda7-416f-9868-b05195a1b973)

![image](https://github.com/hyiso/lint_staged/assets/43802542/e7bae959-c3d6-4c67-a35c-58a7ed05d299)

**Comment by hyiso** [comment]
If this was running on Windows, could you help to check whether https://github.com/lint-staged/lint-staged/issues/1277#issuecomment-1835713010 can help?

**Comment by bawahakim** [comment]
Yup, that seems to work, thanks!

For the lazy: add this `if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then exec >/dev/tty 2>&1; fi` in your `husky/pre-commit` file, before `dart run lint_staged`

**Comment by hyiso** [comment]
Thanks, I'll add this to README later
