### ISSUE TITLE
Help with pubspec.yaml

### ISSUE THREAD

**Issue by Bojan227** [hyiso/lint_staged#16]
```yaml
"lib/**.dart": dart format --fix && dart fix --apply && dart analyze --fatal-infos --fatal-warnings
```
Is it possible to auto-fix the staged files and don't receive any lint error from analyze? With the current line I'm still receiving failing lint step. Thank you!

**Comment by hyiso** [comment]
`dart fix` will auto fix issues that can be fixed.
If you want to ignore lint error, you can either remove `&& dart analyze --fatal-infos --fatal-warnings` or modify `analysis_options.yaml` to disable rules that you do not need.
