### ISSUE TITLE
If i add three  rules in lint staged not performing  first two rules only perform final rule 

### ISSUE THREAD

**Issue by vijaymsc** [hyiso/lint_staged#17]
pubspec.yaml
dev_dependencies:
  husky: 0.1.7
  lint_staged: 0.5.1
lint_staged:
  'lib/**.dart': dart format . -l 120 --fix && dart fix --apply && dart analyze --fatal-infos --fatal-warnings

husky pre_commit file
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

dart run lint_staged

Outpute is 

✗ dart analyze --fatal-infos --fatal-warnings lib/main.dart
Analyzing main.dart...

  error - main.dart:35:3 - Don't invoke 'print' in production code. Try using a logging framework. - avoid_print
   info - main.dart:53:14 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_con
structors

2 issues found.
husky - pre-commit hook exited with code 1 (error)

Expected is 
1. formate the staged file
2. then fix lin  error like const key
3. then check flutter anlyze the issue 

  error - main.dart:35:3 - Don't invoke 'print' in production code. Try using a logging framework. - avoid_print

note: I think first two rules are executed and if run third one before rules are reverted and final result is third rule outputes

**Comment by hyiso** [comment]
Is lib/main.dart in git staged state?(aka `git add lib/main.dart`)

Also, you can add `DEBUG=true` before `dart run lint_staged` in `.husky/pre-commit`  to make the verbose logging message visible

```
DEBUG=true dart run lint_staged
```

**Comment by vijaymsc** [comment]
yes my main.dart file is git added file, i check three scenario  my main.dart file have parint statement and  some methods not  use const key also main.dart file not fomarmated.
i add main.dart file in git and then try  commit my file the pre commit file executed.

Actual Output:-
✗ dart analyze --fatal-infos --fatal-warnings lib/main.dart
Analyzing main.dart...

error - main.dart:35:3 - Don't invoke 'print' in production code. Try using a logging framework. - avoid_print
info - main.dart:53:14 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_con

lint_stageed commands:
lint_staged:
  'lib/**.dart': dart format . -l 120 --fix && dart fix --apply && dart analyze --fatal-infos --fatal-warnings

My goal is:
when i try commit  format  my staged files and auto fix and apply lint issues like const keys and then finely execute  dart analyze still have any issue like print statement  that issue only return in output. not entire analyze issue

**Comment by hyiso** [comment]
If you run these three scripts by hand, does they all succeed or any failure happens?

`lint_staged` will revert tasks' modification when script fails

**Comment by vijaymsc** [comment]
I set 'lib/**.dart': dart format . -l 120 --fix && dart fix --apply && dart analyze --fatal-infos --fatal-warnings. command in pubspec.yaml file.

main.dart have this lint issues
error - main.dart:35:3 - Don't invoke 'print' in production code. Try using a logging framework. - avoid_print
info - main.dart:53:14 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_con

git add lib/main.dart
and try commit the file using lint staged  
again give two issues
error - main.dart:35:3 - Don't invoke 'print' in production code. Try using a logging framework. - avoid_print
info - main.dart:53:14 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_con.


 => dart fix --apply command clear a const key issues in automaticaly and  only give print statement issue but  actual result result is again give two warning const,print in lint staged commit. dart fix --apply  not workking

**Comment by vijaymsc** [comment]
@hyiso thanks for clarification but i need another doubt.

1. my main.dart file only have have const key issue that time dart fix --apply did work right.
    but dart analyze --fatal-infos --fatal-warnings failed with the const key .
2. also when i try to commit my file using lint staged  its take time to long , is there any chance to reduce  commit execution time.

**Comment by vijaymsc** [comment]
Yes i have only  const  key  lint error only dart fix --apply fixed the issue but dart analyze --fatal-infos --fatal-warnings still report the issue

**Comment by hyiso** [comment]
This is unexpected, could you provide a small reproducible code example?

**Comment by zcmgyu** [comment]
Hi @hyiso 
I encountered the same issue. Although I followed the documentation, `lint_staged` still allows many warnings to pass. I don't believe that `dart fix --apply` can address all cases. Therefore, I recommend adding `dart analyze` after running `dart fix` and documenting this step.

**Reproduction steps:**
1. Change a static variable name.
<img width="393" alt="Screenshot 2024-07-06 at 23 35 48" src="https://github.com/hyiso/lint_staged/assets/13638569/1eb3cf9b-aec6-43ea-b723-030d87ad23dc">

2. Ensure that the variable is called somewhere in the code.
<img width="380" alt="Screenshot 2024-07-06 at 23 38 00" src="https://github.com/hyiso/lint_staged/assets/13638569/ee0d48b0-1dcf-4b0c-8b87-c2ecb201ea25">

3. Execute the following commands:
   - `dart fix --apply`
   - `dart analyze`
   
<img width="945" alt="Screenshot 2024-07-06 at 23 32 40" src="https://github.com/hyiso/lint_staged/assets/13638569/0f7b74fd-ee78-443a-a9fc-30553c7b14f8">

**Comment by hyiso** [comment]
Hi @zcmgyu 
According to your comment, the problem is `dart fix` can not fix wrong code in your example.
`lint_staged` does not do code fix, it only runs scripts you configured for git staged files.
