### ISSUE TITLE
ProcessException: Too many open files

### ISSUE THREAD

**Issue by unger1984** [hyiso/lint_staged#9]
Crash with ProcessException: Too many open files ((

64 files in commit

**Comment by hyiso** [comment]
You could add `VERBOSE=true` before the hook script to print verbose error message:
```base
VERBOSE=true dart run lint_staged
```

**Comment by hyiso** [comment]
@cfrias-bardavon 
If this is running on MacOS, could you help to check whether https://github.com/flutter/flutter/issues/18225#issuecomment-396315283 can help?

**Comment by cfrias-bardavon** [comment]
Right, that worked around it, thanks.

**Comment by hyiso** [comment]
OK, I'll update the document later.
